version: '3'

services:
  # Conteneur base de données
  db: 
    image: mongo
    container_name: db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes: 
      # Ce volume permettra de préserver les données si la base de données doit évoluer. Ici, on 
      # se base uniquement sur les données dans le dump, et ce volume n'est pas forcément nécessaire
      - ./data:/data/db
      # On monte le dump de la base de données dans un dossier du conteneur
      - ./dump/test:/dump/
      # On monte le script mongorestore.sh dans le dossier /docker-entrypoint-initdb.d, qui sera 
      # lancé automatiquement au démarrage du conteneur.
      # Ce dossier d'entrypoint est une convention Docker, qui est au moins respectée pour tous les
      # conteneurs de base de données
      - ./dump/mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh:ro
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - "8082:8081"
    depends_on:
      - db
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongo

  front:
    container_name: front
    build: ./front
    ports:
      - "80:80"
    depends_on:
      - back
  back:
    container_name: back
    build: ./back
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - MONGO_URL=mongo
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_PORT=27017
    